name: Deploy
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Deploy site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.X"
    - name: Deploy
      run: | 
        echo "Deploy step goes here."
    
